/*
Use this script to generate calls for the given procedure based on its parameters. This can be useful to automate unit tests after a change on the routine code

*/

SET CONCAT_NULL_YIELDS_NULL OFF
DECLARE @nomeRotina VARCHAR(1000)='ClienteLista',@param VARCHAR(1000),@tipo SMALLINT,@nometipo VARCHAR(500),@tblreferenciada VARCHAR(500),@length INT
,@variaveis VARCHAR(MAX)='',@comandos VARCHAR(MAX)=''+ CHAR(10)

--SELECT p.name,p.system_type_id,t.name,p.* FROM sys.parameters p INNER JOIN sys.procedures pr ON p.object_id = pr.object_id AND pr.name='clientelista' INNER JOIN sys.types t ON p.system_type_id=t.system_type_id AND t.is_user_defined=0
--SELECT * FROM sys.types

SET @tblreferenciada=(SELECT TOP 1 referenced_entity_name
FROM sys.sql_expression_dependencies
WHERE 1=1
--AND referenced_entity_name='vwListaPeloIdSkuNomeProduto'
AND OBJECT_NAME(referencing_id)=@nomeRotina)



DECLARE chamada CURSOR FAST_FORWARD FOR
SELECT p.name,p.system_type_id,t.name,p.max_length FROM sys.parameters p INNER JOIN sys.procedures pr ON p.object_id = pr.object_id AND pr.name=@nomeRotina
INNER JOIN sys.types t ON p.system_type_id=t.system_type_id AND t.is_user_defined=0
AND p.name NOT IN ('@QuantidadeTop','@xmlIdCliente')
ORDER BY parameter_id
OPEN chamada
FETCH NEXT FROM chamada INTO @param,@tipo,@nometipo,@length
WHILE @@FETCH_STATUS<>-1
BEGIN

	SET @variaveis= 'declare ' + @param + ' ' + @nometipo + CASE @tipo WHEN 239 THEN  '('+CONVERT(VARCHAR(100),@length)+')' WHEN 167 THEN '('+CONVERT(VARCHAR(100),@length)+')' END + + '; SELECT TOP 1 ' + @param + '=' + REPLACE(@param,'@','') + ' FROM ' + @tblreferenciada + ' WHERE ' + REPLACE(@param,'@','') + ' is NOT NULL ORDER BY '+REPLACE(@param,'@','')+' DESC; ' + CHAR(10)
	
	SET @comandos = '--parametro: ' + @param + CHAR(10) + 'exec ' + @nomeRotina + ' ' + @param + ' = ' + @param 
	+CHAR(10)
	+'exec ' + @nomeRotina + '2 ' + @param + ' = ' + @param + CHAR(10)+ CHAR(10)
	
	PRINT @variaveis + @comandos

FETCH NEXT FROM chamada INTO @param,@tipo,@nometipo,@length
END
CLOSE chamada
DEALLOCATE chamada


-- the below section is optional and can be used case you want to grab the results generated above and store them in a table for further analysis
/*
-- step 01 - configurar opções de servidor (configure server options)
use master
GO
sp_configure 'Show Advanced Options', 1
GO
RECONFIGURE
GO
sp_configure 'Ad Hoc Distributed Queries', 1
GO
RECONFIGURE
GO

-- step 02 - store the results generated by procedure exectutions in a table. To use the OPENQUERY feature you have to enable 'Ad Hoc Distributed Queries' in your server

IF OBJECT_ID('tempdb..#Procedure1') IS NOT NULL
DROP TABLE	#Procedure1
go


SELECT *
INTO #Procedure1
FROM OPENQUERY([CL-HL-HSQLWEB01\HSQLWEB01], 'exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''d646ae67-dd84-452d-8fca-b744ceaf23bd'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''67aaba8e-d75f-4220-b560-68abce16206b'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=NULL;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''a0f25144-c756-4bd9-ae9a-b53e119a9c90'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''0bcd44b1-ff2f-4b77-bf4f-cd75c5f02945'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''ec1feb09-e91d-46af-94f0-81a3163eeae8'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''67aaba8e-d75f-4220-b560-68abce16206b'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''fc32fe27-7aac-4f16-ba5a-48f47a85cb05'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''e012a187-bbe6-4bed-9f5a-47e7fb2c7348'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''e012a187-bbe6-4bed-9f5a-47e7fb2c7348'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''8f4e3e2a-ce44-480c-9f74-07a3480aa01a'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''c4e927e0-6ba7-4f91-a18e-a00f1c917604'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''14197d4f-110e-462c-a8f0-3365045010e0'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''2c500faf-61e8-4345-aa02-fa4ed6bb3168'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''1fd02f17-0d4e-4af1-84be-921755485363'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''a1c85819-dfff-4ae9-8895-5f10b72c9b4a'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''e012a187-bbe6-4bed-9f5a-47e7fb2c7348'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=NULL;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''27786e67-a187-4e72-af7a-03f3d2944f2f'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''084e3b8f-2ae5-4ed2-8fd0-c5e4d9ebc321'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''b083244d-2e60-43c6-8cf4-f05ab07e1ec3'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''31e7b855-08f4-4d5d-999c-a69a379f972a'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=NULL;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''723ca164-5370-4513-b555-dbf2b271ee26'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''51ca7e4e-8482-4e6c-9f4e-f513e96e6b22'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=NULL;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''3cb0b40d-ab31-46b9-8d5c-65f67f2eaab0'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''46b84ad6-dc04-4858-ba95-4568d3ad4872'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''32f1988f-b594-498e-98d3-b711830484a9'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''aab54699-cdc6-437c-979c-5a6ff7d8e228'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''eeac7ea2-20e0-45e3-9646-6bc75b12c7da'';
exec db_hom_extra.dbo.ClienteLista @IdCliente=8453833,@UsuarioGUID=default,@Nome=default,@Email=default,@Senha=default,@QuantidadeTop=100,@CpfCnpj=default;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''cc13a3db-2266-4036-ad7c-b4b915319ebe'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''94df62d5-b7f6-4084-9c46-6d7896266f05'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''b083244d-2e60-43c6-8cf4-f05ab07e1ec3'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''081122fd-42d4-428d-b12a-680bd5aa8a07'';
exec db_hom_extra.dbo.ClienteLista @IdCliente=7267697,@UsuarioGUID=default,@Nome=default,@Email=default,@Senha=default,@QuantidadeTop=100,@CpfCnpj=default;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=NULL;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''081122fd-42d4-428d-b12a-680bd5aa8a07'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''081122fd-42d4-428d-b12a-680bd5aa8a07'';
exec db_hom_extra.dbo.ClienteLista @IdCliente=8476006,@UsuarioGUID=default,@Nome=default,@Email=default,@Senha=default,@QuantidadeTop=100,@CpfCnpj=default;
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''599da184-f080-47ba-8d86-1d7e0602f926'';
exec db_hom_extra.dbo.ClienteLista @UsuarioGUID=N''3cb0b40d-ab31-46b9-8d5c-65f67f2eaab0'';
exec db_hom_extra.dbo.ClienteLista @IdCliente=8458564,@UsuarioGUID=default,@Nome=default,@Email=default,@Senha=default,@QuantidadeTop=100,@CpfCnpj=default;
')
*/