------ Para habilitar

ALTER DATABASE db_hom_extra
SET CHANGE_TRACKING = ON
(CHANGE_RETENTION = 2 HOURS, AUTO_CLEANUP = ON)

ALTER TABLE dbo.DadosConfiguracao
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = OFF);

ALTER TABLE dbo.DadosRecursos
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = OFF);

ALTER TABLE dbo.Categoria
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = OFF);

ALTER TABLE dbo.FaixaPreco
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = OFF);


