                                                                                                                                                                       
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
deny insert,delete on Administrador to AdmReplicacao                                                                                                                   
deny insert,delete on Campo to AdmReplicacao                                                                                                                           
deny insert,delete on CampoValor to AdmReplicacao                                                                                                                      
deny insert,delete on CanalVenda to AdmReplicacao                                                                                                                      
deny insert,delete on Categoria to AdmReplicacao                                                                                                                       
deny insert,delete on CategoriaArvoreFilho to AdmReplicacao                                                                                                            
deny insert,delete on CategoriaArvorePai to AdmReplicacao                                                                                                              
deny insert,delete on CategoriaSimilar to AdmReplicacao                                                                                                                
deny insert,delete on ColecaoModelo to AdmReplicacao                                                                                                                   
deny insert,delete on ColecaoTipo to AdmReplicacao                                                                                                                     
deny insert,delete on CompraEntregaStatus to AdmReplicacao                                                                                                             
deny insert,delete on Controle to AdmReplicacao                                                                                                                        
deny insert,delete on DicionarioCaptcha to AdmReplicacao                                                                                                               
deny insert,delete on Estoque to AdmReplicacao                                                                                                                         
deny insert,delete on Fabricante to AdmReplicacao                                                                                                                      
deny insert,delete on FaixaPreco to AdmReplicacao                                                                                                                      
deny insert,delete on FasePedido to AdmReplicacao                                                                                                                      
deny insert,delete on Feriado to AdmReplicacao                                                                                                                         
deny insert,delete on Filial to AdmReplicacao                                                                                                                          
deny insert,delete on FormaPagamento to AdmReplicacao                                                                                                                  
deny insert,delete on FormaPagamentoSige to AdmReplicacao                                                                                                              
deny insert,delete on Fornecedor to AdmReplicacao                                                                                                                      
deny insert,delete on FreteEntregaTipo to AdmReplicacao                                                                                                                
deny insert,delete on FreteModalTipo to AdmReplicacao                                                                                                                  
deny insert,delete on Grupo to AdmReplicacao                                                                                                                           
deny insert,delete on GuiaVisual to AdmReplicacao                                                                                                                      
deny insert,delete on Marca to AdmReplicacao                                                                                                                           
deny insert,delete on NomenclaturaBrasileiraMercadoria to AdmReplicacao                                                                                                
deny insert,delete on Perfil to AdmReplicacao                                                                                                                          
deny insert,delete on PerfilRecursoSeguro to AdmReplicacao                                                                                                             
deny insert,delete on Produto to AdmReplicacao                                                                                                                         
deny insert,delete on ProdutoCampoValor to AdmReplicacao                                                                                                               
deny insert,delete on ProdutoCategoriaSimilar to AdmReplicacao                                                                                                         
deny insert,delete on RecursoSeguro to AdmReplicacao                                                                                                                   
deny insert,delete on ResenhaInteresse to AdmReplicacao                                                                                                                
deny insert,delete on Sku to AdmReplicacao                                                                                                                             
deny insert,delete on SkuCondicaoComercial to AdmReplicacao                                                                                                            
deny insert,delete on SkuEan to AdmReplicacao                                                                                                                          
deny insert,delete on SkuKitFilho to AdmReplicacao                                                                                                                     
deny insert,delete on SkuServico to AdmReplicacao                                                                                                                      
deny insert,delete on SkuServicoPrefixoExcecao to AdmReplicacao                                                                                                        
deny insert,delete on SkuServicoTipo to AdmReplicacao                                                                                                                  
deny insert,delete on TipoCampo to AdmReplicacao                                                                                                                       
deny insert,delete on TipoProgramaRecompensa to AdmReplicacao                                                                                                          
deny insert,delete on TipoSku to AdmReplicacao                                                                                                                         
deny insert,delete on ValeStatus to AdmReplicacao                                                                                                                      
