  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Administrador
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.Campo
  DENY_DATABASE - dbo.CampoValor
  DENY_DATABASE - dbo.CampoValor
  DENY_DATABASE - dbo.CampoValor
  DENY_DATABASE - dbo.CampoValor
  DENY_DATABASE - dbo.CampoValor
  DENY_DATABASE - dbo.CampoValor
  DENY_DATABASE - dbo.CanalVenda
  DENY_DATABASE - dbo.CanalVenda
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.Categoria
  DENY_DATABASE - dbo.CategoriaArvoreFilho
  DENY_DATABASE - dbo.CategoriaArvoreFilho
  DENY_DATABASE - dbo.CategoriaArvoreFilho
  DENY_DATABASE - dbo.CategoriaArvoreFilho
  DENY_DATABASE - dbo.CategoriaArvorePai
  DENY_DATABASE - dbo.CategoriaArvorePai
  DENY_DATABASE - dbo.CategoriaArvorePai
  DENY_DATABASE - dbo.CategoriaArvorePai
  DENY_DATABASE - dbo.CategoriaSimilar
  DENY_DATABASE - dbo.CategoriaSimilar
  DENY_DATABASE - dbo.CategoriaSimilar
  DENY_DATABASE - dbo.CategoriaSimilar
  DENY_DATABASE - dbo.ColecaoModelo
  DENY_DATABASE - dbo.ColecaoModelo
  DENY_DATABASE - dbo.ColecaoTipo
  DENY_DATABASE - dbo.ColecaoTipo
  DENY_DATABASE - dbo.ColecaoTipo
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.CompraEntregaStatus
  DENY_DATABASE - dbo.Controle
  DENY_DATABASE - dbo.Controle
  DENY_DATABASE - dbo.Controle
  DENY_DATABASE - dbo.Controle
  DENY_DATABASE - dbo.Controle
  DENY_DATABASE - dbo.DicionarioCaptcha
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Estoque
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.Fabricante
  DENY_DATABASE - dbo.FaixaPreco
  DENY_DATABASE - dbo.FaixaPreco
  DENY_DATABASE - dbo.FaixaPreco
  DENY_DATABASE - dbo.FaixaPreco
  DENY_DATABASE - dbo.FaixaPreco
  DENY_DATABASE - dbo.FasePedido
  DENY_DATABASE - dbo.FasePedido
  DENY_DATABASE - dbo.Feriado
  DENY_DATABASE - dbo.Feriado
  DENY_DATABASE - dbo.Filial
  DENY_DATABASE - dbo.Filial
  DENY_DATABASE - dbo.Filial
  DENY_DATABASE - dbo.Filial
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamento
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.FormaPagamentoSige
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.Fornecedor
  DENY_DATABASE - dbo.FreteEntregaTipo
  DENY_DATABASE - dbo.FreteEntregaTipo
  DENY_DATABASE - dbo.FreteEntregaTipo
  DENY_DATABASE - dbo.FreteEntregaTipo
  DENY_DATABASE - dbo.FreteEntregaTipo
  DENY_DATABASE - dbo.FreteEntregaTipo
  DENY_DATABASE - dbo.FreteModalTipo
  DENY_DATABASE - dbo.FreteModalTipo
  DENY_DATABASE - dbo.Grupo
  DENY_DATABASE - dbo.Grupo
  DENY_DATABASE - dbo.Grupo
  DENY_DATABASE - dbo.Grupo
  DENY_DATABASE - dbo.Grupo
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.GuiaVisual
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.Marca
  DENY_DATABASE - dbo.NomenclaturaBrasileiraMercadoria
  DENY_DATABASE - dbo.NomenclaturaBrasileiraMercadoria
  DENY_DATABASE - dbo.NomenclaturaBrasileiraMercadoria
  DENY_DATABASE - dbo.Perfil
  DENY_DATABASE - dbo.Perfil
  DENY_DATABASE - dbo.PerfilRecursoSeguro
  DENY_DATABASE - dbo.PerfilRecursoSeguro
  DENY_DATABASE - dbo.PerfilRecursoSeguro
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.Produto
  DENY_DATABASE - dbo.ProdutoCampoValor
  DENY_DATABASE - dbo.ProdutoCampoValor
  DENY_DATABASE - dbo.ProdutoCampoValor
  DENY_DATABASE - dbo.ProdutoCampoValor
  DENY_DATABASE - dbo.ProdutoCampoValor
  DENY_DATABASE - dbo.ProdutoCategoriaSimilar
  DENY_DATABASE - dbo.ProdutoCategoriaSimilar
  DENY_DATABASE - dbo.RecursoSeguro
  DENY_DATABASE - dbo.RecursoSeguro
  DENY_DATABASE - dbo.RecursoSeguro
  DENY_DATABASE - dbo.RecursoSeguro
  DENY_DATABASE - dbo.ResenhaInteresse
  DENY_DATABASE - dbo.ResenhaInteresse
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.Sku
  DENY_DATABASE - dbo.SkuCondicaoComercial
  DENY_DATABASE - dbo.SkuCondicaoComercial
  DENY_DATABASE - dbo.SkuCondicaoComercial
  DENY_DATABASE - dbo.SkuEan
  DENY_DATABASE - dbo.SkuEan
  DENY_DATABASE - dbo.SkuEan
  DENY_DATABASE - dbo.SkuEan
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuKitFilho
  DENY_DATABASE - dbo.SkuServico
  DENY_DATABASE - dbo.SkuServico
  DENY_DATABASE - dbo.SkuServico
  DENY_DATABASE - dbo.SkuServico
  DENY_DATABASE - dbo.SkuServico
  DENY_DATABASE - dbo.SkuServico
  DENY_DATABASE - dbo.SkuServicoPrefixoExcecao
  DENY_DATABASE - dbo.SkuServicoTipo
  DENY_DATABASE - dbo.SkuServicoTipo
  DENY_DATABASE - dbo.SkuServicoTipo
  DENY_DATABASE - dbo.TipoCampo
  DENY_DATABASE - dbo.TipoCampo
  DENY_DATABASE - dbo.TipoCampo
  DENY_DATABASE - dbo.TipoCampo
  DENY_DATABASE - dbo.TipoProgramaRecompensa
  DENY_DATABASE - dbo.TipoProgramaRecompensa
  DENY_DATABASE - dbo.TipoSku
  DENY_DATABASE - dbo.TipoSku
  DENY_DATABASE - dbo.ValeStatus
  DENY_DATABASE - dbo.ValeStatus
