-- run this script to validate all the constraints within the database. The script will store inconsistencies in a separate table
-- for reporting purposes

IF OBJECT_ID('DBA.DBO.CHECKCONSTRAINTS') IS NULL AND DB_ID('DBA') IS NOT NULL
BEGIN
	CREATE TABLE DBA.DBO.CHECKCONSTRAINTS (TABELA VARCHAR(500),FK VARCHAR(500), CONDICAO VARCHAR(1000))
END

IF OBJECT_ID('DBA.DBO.CHECKCONSTRAINTS') IS NOT NULL
BEGIN
	INSERT DBA.DBO.CHECKCONSTRAINTS
	EXEC('DBCC CHECKCONSTRAINTS WITH ALL_CONSTRAINTS, NO_INFOMSGS')
END
ELSE
	PRINT 'BANCO DBA NÃO EXISTE'


SELECT * FROM DBA.DBO.CHECKCONSTRAINTS